window_height = 700
window_right_gap = 300
window_width = window_height + window_right_gap
picture_tl_corner = (-100, 100)
picture_br_corner = (100, -100)
max_number_of_iterations = 5000
iteration_step_precision = 0.001
phase_line_color = 'blue'
phase_line_density = 7
axes_boarder_gap = 70
axes_color = 'black'
axes_thickness = 3
axes_marks_thickness = 2
axes_mark_number = 6
axes_mark_length = 7
axes_mark_numbers_offset = 5
axes_mark_numbers_font = 'Arial 10 bold'
axes_mark_color = 'black'
fps = 60
frame_time = 1/fps
scale_change_factor = 1.5
